// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.tsx";
import * as $1 from "./routes/api/rifffData.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/rifff/[rifffId].tsx";
import * as $$0 from "./islands/CopyButton.tsx";
import * as $$1 from "./islands/LinkConvertor.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.tsx": $0,
    "./routes/api/rifffData.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/rifff/[rifffId].tsx": $3,
  },
  islands: {
    "./islands/CopyButton.tsx": $$0,
    "./islands/LinkConvertor.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
